// lib/mediaStorage.ts
// Media storage backend — writes to local disk under public/uploads/media/,
// served by Next.js as ordinary static files. This project runs on a VPS
// with a persistent filesystem (not a serverless/read-only environment like
// Vercel), so local disk is a real, permanent storage backend here — not a
// stopgap. Every consumer (CMS media, admin/B2B/community/forms uploads)
// goes through this single module; nothing else touches the filesystem or
// generates a storage key.
import { randomBytes } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { imageSize } from "image-size";

export const MEDIA_UPLOAD_POLICY = {
  types: ["image/jpeg", "image/png", "image/webp", "image/gif"] as const,
  maxSize: 5 * 1024 * 1024,
  maxFiles: 20,
};

const EXTENSIONS: Record<(typeof MEDIA_UPLOAD_POLICY.types)[number], string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
};

// Storage keys are always generated by us (random hex + a known-good
// extension) — user input never reaches the filesystem path, so path
// traversal isn't reachable through the key itself. This regex is a second,
// defense-in-depth check applied again before every delete/replace/serve.
const STORAGE_KEY_RE = /^media\/[a-f0-9]{32}\.(jpg|jpeg|png|webp|gif)$/;

const UPLOAD_ROOT = path.join(process.cwd(), "public", "uploads");
const PUBLIC_URL_PREFIX = "/uploads";

export class UploadValidationError extends Error {}

export type UploadedMediaAsset = {
  url: string;
  publicId: string;
  filename: string;
  mimeType: string;
  size: number;
  width?: number;
  height?: number;
};

function hasValidSignature(type: string, bytes: Uint8Array) {
  if (bytes.length < 12) return false;
  if (type === "image/jpeg") return bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff;
  if (type === "image/png")
    return bytes
      .slice(0, 8)
      .every((byte, index) => byte === [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a][index]);
  if (type === "image/gif")
    return ["GIF87a", "GIF89a"].includes(new TextDecoder().decode(bytes.slice(0, 6)));
  if (type === "image/webp")
    return (
      new TextDecoder().decode(bytes.slice(0, 4)) === "RIFF" &&
      new TextDecoder().decode(bytes.slice(8, 12)) === "WEBP"
    );
  return false;
}

export async function validateMediaFile(file: File) {
  if (!(MEDIA_UPLOAD_POLICY.types as readonly string[]).includes(file.type))
    throw new UploadValidationError(`File type ${file.type || "unknown"} is not allowed`);
  if (!file.size || file.size > MEDIA_UPLOAD_POLICY.maxSize)
    throw new UploadValidationError(
      `File ${file.name || "unnamed"} exceeds the 5 MB limit or is empty`,
    );
  if (
    !file.name ||
    file.name.length > 180 ||
    /[\\/\0-\x1f]/.test(file.name) ||
    file.name === "." ||
    file.name === ".."
  )
    throw new UploadValidationError("Invalid filename");
  const extension = file.name.split(".").pop()?.toLowerCase() ?? "";
  const declaredExtensions: Record<string, readonly string[]> = {
    "image/jpeg": ["jpg", "jpeg"],
    "image/png": ["png"],
    "image/webp": ["webp"],
    "image/gif": ["gif"],
  };
  if (!declaredExtensions[file.type]?.includes(extension))
    throw new UploadValidationError("File extension does not match its media type");
  const buffer = Buffer.from(await file.arrayBuffer());
  if (!hasValidSignature(file.type, buffer))
    throw new UploadValidationError("File content does not match its declared media type");
  return buffer;
}

/** Resolves a storage key to an absolute path, refusing to leave UPLOAD_ROOT. */
function resolveStoragePath(key: string) {
  if (!STORAGE_KEY_RE.test(key)) throw new UploadValidationError("Invalid storage key");
  const resolved = path.join(UPLOAD_ROOT, key);
  if (!resolved.startsWith(UPLOAD_ROOT + path.sep))
    throw new UploadValidationError("Invalid storage key");
  return resolved;
}

function newStorageKey(mimeType: string) {
  const extension = EXTENSIONS[mimeType as keyof typeof EXTENSIONS];
  return `media/${randomBytes(16).toString("hex")}.${extension}`;
}

function readDimensions(buffer: Buffer): { width?: number; height?: number } {
  try {
    const { width, height } = imageSize(buffer);
    return { width, height };
  } catch {
    // Dimensions are informational only — never fail an otherwise-valid
    // upload just because a corner-case file couldn't be measured.
    return {};
  }
}

async function writeAsset(key: string, buffer: Buffer) {
  const filePath = resolveStoragePath(key);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, buffer, { flag: "wx" }); // wx: never silently overwrite
}

export async function uploadMediaAssets(files: File[]): Promise<UploadedMediaAsset[]> {
  if (!files?.length) throw new UploadValidationError("No files provided");
  if (files.length > MEDIA_UPLOAD_POLICY.maxFiles)
    throw new UploadValidationError(`Upload at most ${MEDIA_UPLOAD_POLICY.maxFiles} files at once`);
  const buffers = await Promise.all(files.map(validateMediaFile));
  const assets: UploadedMediaAsset[] = [];
  try {
    for (const [index, file] of files.entries()) {
      const buffer = buffers[index];
      const key = newStorageKey(file.type);
      await writeAsset(key, buffer);
      const { width, height } = readDimensions(buffer);
      assets.push({
        url: `${PUBLIC_URL_PREFIX}/${key}`,
        publicId: key,
        filename: file.name,
        mimeType: file.type,
        size: buffer.byteLength,
        width,
        height,
      });
    }
  } catch (error) {
    await Promise.allSettled(assets.map((asset) => deleteMediaAsset(asset.publicId)));
    throw error;
  }
  return assets;
}

export async function uploadImages(files: File[]): Promise<string[]> {
  return (await uploadMediaAssets(files)).map((asset) => asset.url);
}

export async function deleteMediaAsset(publicId: string) {
  const filePath = resolveStoragePath(publicId);
  try {
    await unlink(filePath);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return; // already gone — treat as success
    throw new Error("Storage deletion failed");
  }
}

export async function replaceMediaAsset(publicId: string, file: File): Promise<UploadedMediaAsset> {
  resolveStoragePath(publicId); // validate before doing any work
  const buffer = await validateMediaFile(file);
  const filePath = resolveStoragePath(publicId);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, buffer); // in-place overwrite — same key, same URL, references preserved
  const { width, height } = readDimensions(buffer);
  return {
    url: `${PUBLIC_URL_PREFIX}/${publicId}`,
    publicId,
    filename: file.name,
    mimeType: file.type,
    size: buffer.byteLength,
    width,
    height,
  };
}
