// Dynamic OG image generated by Next.js ImageResponse
// ═══════════════════════════════════════════════════════════════════════════════

import { ImageResponse } from "next/og";

export const runtime = "edge";
export const alt = "Calma Trip — Stress-Free Travel in Tunisia";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OGImage() {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-end",
        background: "#0C1F14",
        padding: "64px",
        fontFamily: "sans-serif",
      }}
    >
      {/* Top label */}
      <div
        style={{
          position: "absolute",
          top: "48px",
          left: "64px",
          display: "flex",
          alignItems: "center",
          gap: "10px",
          background: "rgba(76,175,80,0.15)",
          border: "1px solid rgba(76,175,80,0.4)",
          borderRadius: "50px",
          padding: "8px 20px",
        }}
      >
        <div
          style={{
            width: "8px",
            height: "8px",
            borderRadius: "50%",
            background: "#D2B38B",
          }}
        />
        <span
          style={{ color: "#D2B38B", fontSize: "13px", fontWeight: 700, letterSpacing: "0.15em" }}
        >
          STRESS-FREE TRAVEL IN TUNISIA
        </span>
      </div>

      {/* Main headline */}
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <div style={{ fontSize: "72px", fontWeight: 900, color: "#ffffff", lineHeight: 1.05 }}>
          Calma Trip
        </div>
        <div
          style={{
            fontSize: "28px",
            color: "#F0E2CE",
            fontWeight: 400,
            maxWidth: "700px",
            lineHeight: 1.4,
          }}
        >
          Private transfers · Excursions · Local prices
        </div>
      </div>

      {/* Bottom strip */}
      <div
        style={{
          position: "absolute",
          bottom: "0",
          left: "0",
          right: "0",
          height: "4px",
          background: "#D2B38B",
        }}
      />
    </div>,
    { ...size },
  );
}
